// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A skill Jev rated as a high-confidence fit for the current request.
 */
export type SkillSuggestion = { name: string, fitProbability: number, };
