// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSuggestion } from "./SkillSuggestion";
import type { SkillSuggestionStatus } from "./SkillSuggestionStatus";

/**
 * Status of Jev's advisory skill-selection pass for a turn.
 */
export type SkillSuggestionNotification = { threadId: string, turnId: string, status: SkillSuggestionStatus, suggestions: Array<SkillSuggestion>, };
