// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether Jev returned strong skill matches, no match, or could not complete the check.
 */
export type SkillSuggestionStatus = "suggested" | "noMatch" | "unavailable";
